### ISSUE TITLE
DTGenerationSupportToolはまだ必要ですか？

### ISSUE THREAD

**Issue by korosuke613** [HirokiTachiyama/BWDM#14]
デシジョンテーブルの生成ツールかと思うのですが、今のBWDMはZ3Solverを使うことで、デシジョンテーブルの生成はできますよね？

**Comment by HirokiTachiyama** [comment]
>　デシジョンテーブルの生成ツールかと思うのですが

正解

> 今のBWDMはZ3Solverを使うことで、デシジョンテーブルの生成はできますよね？

その通り

なので、Issueへの回答は「消しておk」です。
何故残しておいたかと言うと……「なんとなく」だった気がする。すみませぬ

**Comment by korosuke613** [comment]
ありがとうございまんぐーす！（MYJ）
`tools`みたいなディレクトリ作って避難させて起きまする(⊙ω⊙)v
